In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
python_list=[5,15,-5,8,2]

In [4]:
python_list

[5, 15, -5, 8, 2]

In [5]:
numpy_arr=np.array(python_list)

In [18]:
numpy_arr.shape

(5,)

In [6]:
len=len(numpy_arr.shape)

In [7]:
len

1

In [8]:
type(numpy_arr)

numpy.ndarray

In [9]:
python_list_list=[[1,2],[3,4]]

In [10]:
python_list_list

[[1, 2], [3, 4]]

In [11]:
numpy_arr_arr=np.array(python_list_list)

In [12]:
numpy_arr_arr

array([[1, 2],
       [3, 4]])

In [15]:
numpy_arr_arr.shape

(2, 2)

In [20]:
list(range(5))

[0, 1, 2, 3, 4]

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.random.randint(9,size=(2,2))

array([[3, 1],
       [5, 6]])