In [1]:
import numpy as np

In [2]:
marks=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [3]:
marks

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [10]:
marks_trans=[]
for i in range(len(marks[0])):
    marks_trans.append([])
    for j in range(len(marks)):
        marks_trans[i].append(marks[j][i])

In [11]:
marks_trans

[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]

In [12]:
marks_arr=np.array(marks)

In [13]:
marks_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
marks_arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [17]:
marks_arr.sum(axis=1)

array([ 6, 15, 24, 33])

In [30]:
grace_marks=[[1,2,3,4]]

In [33]:
grace_arr=np.array(grace_marks).T

In [34]:
grace_arr

array([[1],
       [2],
       [3],
       [4]])

In [35]:
marks_arr+grace_arr #broadcasting

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [48]:
weight=[[0.2,0.5,0.2]]

In [49]:
weight_arr=np.array(weight).T

In [50]:
weight_arr.shape

(3, 1)

In [51]:
marks_arr.shape

(4, 3)

In [53]:
marks_arr @ weight_arr # matrix multiplication

array([[1.8],
       [4.5],
       [7.2],
       [9.9]])