In [3]:
import numpy as np

In [39]:
# Basics

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
(type(arr1))

numpy.ndarray

In [35]:
arr1.dtype

dtype('int32')

In [17]:
arr1.ndim

1

In [18]:
arr2.ndim

2

In [20]:
arr1.size

5

In [21]:
arr2.size

12

In [22]:
arr1.shape

(5,)

In [23]:
arr2.shape

(3, 4)

In [31]:
arr3=np.ones(shape=(3,4),dtype=int)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
arr3.dtype

dtype('int32')

In [33]:
arr4=np.zeros((3,4),int)

In [34]:
arr4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
arr4.astype(float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
#Arange functions

In [42]:
arr5=np.arange(1,10)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr6=np.arange(1,20,2)
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
arr2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [46]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
arr7=np.linspace(1,10,5)

In [56]:
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [57]:
# Mathematics operation in numpy

In [63]:
arr9=np.add(arr2,arr3)
arr9

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [64]:
arr10=np.subtract(arr2,arr3)
arr10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.multiply(arr2,arr10)

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [66]:
np.divide(arr2,arr9)

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889],
       [0.9       , 0.90909091, 0.91666667, 0.92307692]])

In [67]:
arr11=np.array([[1,2],[3,4],[5,6],[7,8]])

In [68]:
arr2@arr11

array([[ 50,  60],
       [114, 140],
       [178, 220]])

In [73]:
arr2.dot(arr11)

array([[ 50,  60],
       [114, 140],
       [178, 220]])

In [75]:
arr2.max()

12

In [76]:
arr2.max(axis=0)

array([ 9, 10, 11, 12])

In [77]:
arr2.max(axis=1)

array([ 4,  8, 12])

In [78]:
arr2.min()

1

In [79]:
arr2.min(axis=0)

array([1, 2, 3, 4])

In [80]:
arr2.min(axis=1)

array([1, 5, 9])

In [82]:
np.mean(arr2)

6.5

In [83]:
np.std(arr2)

3.452052529534663

In [84]:
np.exp(arr2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [90]:
np.log10(arr2)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])